#!/bin/sh
# Install the shed CLI.
#
#   curl -fsSL https://raw.githubusercontent.com/shed-sh/cli/main/install-cli.sh | sh
#
# The actual install is done by the `shed-installer.sh` attached to each
# release. That installer is generated by the same tool that builds the release
# artifacts, so its download URLs, archive names, and platform detection can
# never disagree with the assets it ships beside — this script only picks which
# release's installer to run.
set -eu

REPO="shed-sh/cli"
BIN_DIR="${SHED_BIN_DIR:-}"
VERSION="${SHED_VERSION:-latest}"

usage() {
	cat <<'EOF'
Install the shed CLI.

Usage: install.sh [options]
       install-cli.sh [options]

  --version <v>     Install a specific version (default: the latest release)
  --bin-dir <dir>   Where to put the binary (default: ~/.local/bin, or the
                    XDG bin directory when one is configured)
  -h, --help        Show this message

Environment: SHED_VERSION, SHED_BIN_DIR
EOF
}

while [ $# -gt 0 ]; do
	case "$1" in
	--version)
		VERSION="${2:?--version needs a value}"
		shift 2
		;;
	--bin-dir)
		BIN_DIR="${2:?--bin-dir needs a value}"
		shift 2
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "install-cli.sh: unknown option $1" >&2
		usage >&2
		exit 2
		;;
	esac
done

die() {
	echo "install-cli.sh: $*" >&2
	exit 1
}

command -v curl >/dev/null 2>&1 || die "curl is required but was not found"

if [ "$VERSION" = "latest" ]; then
	installer_url="https://github.com/$REPO/releases/latest/download/shed-installer.sh"
else
	installer_url="https://github.com/$REPO/releases/download/v${VERSION#v}/shed-installer.sh"
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

curl --proto '=https' --proto-redir '=https' -fsSL "$installer_url" -o "$tmp/shed-installer.sh" ||
	die "could not download the installer for '$VERSION' from $REPO.
Check that the version exists and has published releases."

# SHED_INSTALL_DIR forces a flat install into exactly that directory; without
# it the installer walks its configured path candidates, ending at ~/.local/bin.
if [ -n "$BIN_DIR" ]; then
	SHED_INSTALL_DIR="$BIN_DIR" sh "$tmp/shed-installer.sh"
else
	sh "$tmp/shed-installer.sh"
fi
