package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"time"

	"shed/internal/clispec"
	"shed/internal/diag"
)

// releasesURLEnv overrides where upgrades are looked up. Deliberately
// undocumented, for the same reason the control-plane address is: it exists so
// this repository's tests can stand in a fake release host, and someone who
// installed a release has no reason to point upgrades anywhere else.
const releasesURLEnv = "SHED_RELEASES_URL"

const defaultReleasesURL = "https://github.com/shed-sh/cli/releases"

// versionPattern matches the version tags the release pipeline can actually
// produce. Anything else would be interpolated into the download URL, so it
// is rejected before it can name an unexpected path on the release host.
var versionPattern = regexp.MustCompile(`^[0-9A-Za-z][0-9A-Za-z.+-]*$`)

// validateReleaseBase refuses to fetch executable code over plaintext HTTP.
// The installer this command downloads runs with no further verification, so
// TLS to the release host is the one integrity control on the whole path.
// Loopback stays exempt: the tests stand in a local fake release host.
func validateReleaseBase(base string) error {
	parsed, err := url.Parse(base)
	if err != nil {
		return err
	}
	if parsed.Scheme == "https" || isLoopbackHost(parsed.Hostname()) {
		return nil
	}
	return &diag.Error{
		Code:    "upgrade_failed",
		Summary: "refusing to fetch an upgrade over an insecure transport.",
		Facts:   []diag.Fact{{Label: "Release host", Value: base}},
		Hints:   []string{"Use an https:// release URL."},
	}
}

func isLoopbackHost(host string) bool {
	if host == "localhost" {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}

// upgrade replaces this binary with a released one. It resolves the target
// version itself, but delegates the actual swap to the release's own
// shed-installer.sh — the installer is generated by the same pipeline that
// builds the artifacts, so archive names, extraction, and the atomic replace
// live in exactly one place.
func (a *App) upgrade(ctx context.Context, b *clispec.Binding) error {
	executable, refusal := a.upgradableExecutable()
	if refusal != nil {
		return refusal
	}

	base := strings.TrimRight(os.Getenv(releasesURLEnv), "/")
	if base == "" {
		base = defaultReleasesURL
	}
	if err := validateReleaseBase(base); err != nil {
		return err
	}

	target := strings.TrimPrefix(strings.TrimSpace(b.String("version")), "v")
	if target == "" {
		resolved, err := latestReleaseVersion(ctx, base)
		if err != nil {
			return err
		}
		target = resolved
	}
	if !versionPattern.MatchString(target) {
		return &diag.Error{
			Code:    "upgrade_failed",
			Summary: fmt.Sprintf("%q does not look like a release version.", target),
			Hints:   []string{"Name a published version, like: shed upgrade --version 0.1.0"},
		}
	}

	if b.Bool("check") {
		outcome := "update_available"
		if target == a.version {
			outcome = "current"
		}
		return a.reportUpgrade(b, outcome, target)
	}
	if target == a.version {
		return a.reportUpgrade(b, "current", target)
	}

	if err := a.runReleaseInstaller(ctx, base, target, filepath.Dir(executable)); err != nil {
		return err
	}
	if err := verifyInstalledVersion(ctx, executable, target); err != nil {
		return err
	}
	return a.reportUpgrade(b, "upgraded", target)
}

// upgradableExecutable names the binary to replace, refusing the installs
// this command must not touch: a source build has no release to return to,
// and a package-managed binary belongs to its package manager — replacing it
// underneath brew, npm, or pacman corrupts their bookkeeping.
func (a *App) upgradableExecutable() (string, *diag.Error) {
	if a.version == "dev" {
		return "", &diag.Error{
			Code:    "upgrade_unsupported_install",
			Summary: "this shed is a source build, and an upgrade would replace it with a release.",
			Hints:   []string{"Rebuild it from source instead: go build ./cmd/shed"},
		}
	}
	executable, err := a.executablePath()
	if err != nil {
		return "", &diag.Error{
			Code:    "upgrade_failed",
			Summary: "could not determine which binary to replace: " + err.Error(),
			Cause:   err,
		}
	}
	if resolved, resolveErr := filepath.EvalSymlinks(executable); resolveErr == nil {
		executable = resolved
	}
	if manager := managingPackageManager(executable); manager != "" {
		return "", &diag.Error{
			Code:    "upgrade_unsupported_install",
			Summary: "this shed is managed by " + manager + ", which owns its upgrades.",
			Facts:   []diag.Fact{{Label: "Binary", Value: executable}},
			Hints:   []string{"Upgrade it there instead: " + packageManagerUpgrade(manager)},
		}
	}
	return executable, nil
}

// managingPackageManager recognizes an install path that belongs to a package
// manager. Path shape is the tell for brew and npm; on Arch the path is a
// plain /usr/bin, so pacman itself is asked, best-effort.
func managingPackageManager(executable string) string {
	switch {
	case strings.Contains(executable, "/Cellar/") || strings.Contains(executable, "/homebrew/"):
		return "Homebrew"
	case strings.Contains(executable, "/node_modules/"):
		return "npm"
	}
	if runtime.GOOS == "linux" {
		if _, err := exec.LookPath("pacman"); err == nil {
			if exec.Command("pacman", "-Qo", executable).Run() == nil {
				return "pacman"
			}
		}
	}
	return ""
}

func packageManagerUpgrade(manager string) string {
	switch manager {
	case "Homebrew":
		return "brew upgrade shed-sh/tap/shed"
	case "npm":
		return "npm update -g @shed-sh/shed"
	case "pacman":
		return "paru -Syu shed-bin"
	}
	return ""
}

// latestReleaseVersion reads the version out of the /releases/latest redirect,
// the same way install.sh resolves it: no API, no token, no rate limit.
func latestReleaseVersion(ctx context.Context, base string) (string, error) {
	client := &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, base+"/latest", nil)
	if err != nil {
		return "", err
	}
	response, err := client.Do(request)
	if err != nil {
		return "", &diag.Error{
			Code:    "release_unavailable",
			Summary: "could not reach the release host to find the latest version.",
			Facts:   []diag.Fact{{Label: "Tried", Value: base + "/latest"}, {Label: "Cause", Value: err.Error()}},
			Hints:   []string{"Check the network, or name a version: shed upgrade --version <v>"},
			Cause:   err,
		}
	}
	defer func() { _ = response.Body.Close() }()
	location := response.Header.Get("Location")
	// With no published releases the redirect lands on /releases rather than
	// a /tag/<v> page, and a non-redirect answer has no Location at all.
	tag := location[strings.LastIndex(location, "/")+1:]
	if location == "" || !strings.Contains(location, "/tag/") || tag == "" {
		return "", &diag.Error{
			Code:    "release_unavailable",
			Summary: "the release host did not name a latest version.",
			Facts:   []diag.Fact{{Label: "Tried", Value: base + "/latest"}},
			Hints:   []string{"There may be no published releases yet; name one: shed upgrade --version <v>"},
		}
	}
	return strings.TrimPrefix(tag, "v"), nil
}

// runReleaseInstaller downloads the target release's own installer and runs
// it against the directory this binary lives in. SHED_NO_MODIFY_PATH keeps an
// upgrade from re-touching shell profiles; that was install's job.
func (a *App) runReleaseInstaller(ctx context.Context, base, version, directory string) error {
	installerURL := base + "/download/v" + version + "/shed-installer.sh"
	client := &http.Client{
		Timeout: 60 * time.Second,
		// Release downloads legitimately redirect (GitHub hands assets off
		// to a CDN), but never from https to plaintext — a downgrade mid-way
		// would defeat the transport check on the base URL.
		CheckRedirect: func(request *http.Request, via []*http.Request) error {
			if len(via) >= 10 {
				return fmt.Errorf("stopped after 10 redirects")
			}
			if request.URL.Scheme != "https" && !isLoopbackHost(request.URL.Hostname()) {
				return fmt.Errorf("refusing insecure redirect to %s", request.URL.Redacted())
			}
			return nil
		},
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, installerURL, nil)
	if err != nil {
		return err
	}
	response, err := client.Do(request)
	if err == nil && response.StatusCode != http.StatusOK {
		_ = response.Body.Close()
		err = fmt.Errorf("HTTP %d", response.StatusCode)
	}
	if err != nil {
		return &diag.Error{
			Code:    "release_unavailable",
			Summary: fmt.Sprintf("could not download the installer for %s.", version),
			Facts:   []diag.Fact{{Label: "Tried", Value: installerURL}, {Label: "Cause", Value: err.Error()}},
			Hints:   []string{"Check that version " + version + " is a published release."},
			Cause:   err,
		}
	}
	defer func() { _ = response.Body.Close() }()

	installer, err := os.CreateTemp("", "shed-installer-*.sh")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(installer.Name()) }()
	if _, err := installer.ReadFrom(response.Body); err != nil {
		_ = installer.Close()
		return err
	}
	if err := installer.Close(); err != nil {
		return err
	}

	command := exec.CommandContext(ctx, "sh", installer.Name())
	command.Env = append(os.Environ(),
		"SHED_INSTALL_DIR="+directory,
		"SHED_NO_MODIFY_PATH=1",
	)
	command.Stdout = a.stdout
	command.Stderr = a.stderr
	if err := command.Run(); err != nil {
		return &diag.Error{
			Code:    "upgrade_failed",
			Summary: fmt.Sprintf("the %s installer did not finish.", version),
			Facts:   []diag.Fact{{Label: "Cause", Value: err.Error()}},
			Hints:   []string{"The current binary is untouched; read the installer output above."},
			Cause:   err,
		}
	}
	return nil
}

// verifyInstalledVersion asks the binary that now sits at the install path
// what it is, so "upgraded" is a report rather than a hope.
func verifyInstalledVersion(ctx context.Context, executable, version string) error {
	output, err := exec.CommandContext(ctx, executable, "version").Output()
	installed := strings.TrimSpace(string(output))
	if err != nil || installed != version {
		if err == nil {
			err = fmt.Errorf("it reports %q, expected %q", installed, version)
		}
		return &diag.Error{
			Code:    "upgrade_failed",
			Summary: "the installer finished, but the installed binary does not answer as " + version + ".",
			Facts:   []diag.Fact{{Label: "Binary", Value: executable}, {Label: "Cause", Value: err.Error()}},
			Cause:   err,
		}
	}
	return nil
}

// upgradeReport is the one JSON object every upgrade outcome prints.
type upgradeReport struct {
	Type    string `json:"type"`
	Outcome string `json:"outcome"`
	From    string `json:"from"`
	To      string `json:"to"`
}

func (a *App) reportUpgrade(b *clispec.Binding, outcome, target string) error {
	if b.String("output") == "json" {
		return json.NewEncoder(a.stdout).Encode(upgradeReport{
			Type: "result", Outcome: outcome, From: a.version, To: target,
		})
	}
	switch outcome {
	case "current":
		_, _ = fmt.Fprintf(a.stdout, "shed %s is already the newest release.\n", a.version)
	case "update_available":
		_, _ = fmt.Fprintf(a.stdout, "shed %s is available; you have %s. Run: shed upgrade\n", target, a.version)
	case "upgraded":
		_, _ = fmt.Fprintf(a.stdout, "Upgraded shed %s → %s.\n", a.version, target)
	}
	return nil
}
