package docs

import (
	"embed"
	"fmt"
	"strings"
	"text/template"

	"shed/internal/clispec"
	"shed/internal/shedfile"
)

//go:embed templates/*.tmpl
var templates embed.FS

// reference is the template's view of the command surface.
type reference struct {
	Groups      []clispec.Group
	Environment []clispec.EnvVar
}

var funcs = template.FuncMap{
	// cell escapes the pipes in values like "human|json|ndjson", which would
	// otherwise split a markdown table cell in two.
	"cell": func(value string) string {
		return strings.ReplaceAll(value, "|", `\|`)
	},
	"aliases": func(values []string) string {
		quoted := make([]string, 0, len(values))
		for _, value := range values {
			quoted = append(quoted, "`"+value+"`")
		}
		return joinWithOr(quoted)
	},
	// examples renders an aligned invocation block, so the commands and their
	// comments read as two columns rather than a ragged line.
	"examples": func(values []clispec.Example) string {
		width := 0
		for _, example := range values {
			if len(example.Command) > width {
				width = len(example.Command)
			}
		}
		var out strings.Builder
		for _, example := range values {
			if example.Comment == "" {
				fmt.Fprintf(&out, "%s\n", example.Command)
				continue
			}
			fmt.Fprintf(&out, "%-*s   # %s\n", width, example.Command, example.Comment)
		}
		return strings.TrimRight(out.String(), "\n")
	},
	"exclusives": func(groups [][]string) string {
		rendered := make([]string, 0, len(groups))
		for _, group := range groups {
			names := make([]string, 0, len(group))
			for _, name := range group {
				names = append(names, "`--"+name+"`")
			}
			rendered = append(rendered, strings.Join(names, " with "))
		}
		return strings.Join(rendered, "; ")
	},
}

func joinWithOr(values []string) string {
	switch len(values) {
	case 0:
		return ""
	case 1:
		return values[0]
	case 2:
		return values[0] + " or " + values[1]
	default:
		return strings.Join(values[:len(values)-1], ", ") + ", or " + values[len(values)-1]
	}
}

// RenderCommandsReference produces the whole command reference document.
func RenderCommandsReference() (string, error) {
	parsed, err := template.New("commands.md.tmpl").Funcs(funcs).ParseFS(templates, "templates/commands.md.tmpl")
	if err != nil {
		return "", err
	}
	var out strings.Builder
	if err := parsed.Execute(&out, reference{Groups: clispec.Groups, Environment: clispec.Environment}); err != nil {
		return "", err
	}
	return tidy(out.String()), nil
}

// starlarkReference is the template's view of the SHED language surface. The
// builtins come straight from the evaluator's spec tables, so a function this
// document describes is a function the evaluator accepts, argument for
// argument.
type starlarkReference struct {
	FileName        string
	Builtins        []shedfile.SchemaBuiltin
	NotYetSupported string
}

// RenderStarlarkReference produces the whole SHED language reference document.
func RenderStarlarkReference() (string, error) {
	parsed, err := template.New("starlark.md.tmpl").Funcs(funcs).ParseFS(templates, "templates/starlark.md.tmpl")
	if err != nil {
		return "", err
	}
	schema := shedfile.APISchema()
	var out strings.Builder
	if err := parsed.Execute(&out, starlarkReference{
		FileName:        schema.File,
		Builtins:        schema.Builtins,
		NotYetSupported: strings.Join(schema.NotYetSupported, ", "),
	}); err != nil {
		return "", err
	}
	return tidy(out.String()), nil
}

// RenderCommandTable is the compact listing injected into SKILL.md, where the
// surrounding narrative is hand-written and only the facts are generated.
func RenderCommandTable() string {
	var out strings.Builder
	out.WriteString("| Command | Purpose |\n|---|---|\n")
	for _, command := range clispec.Commands() {
		fmt.Fprintf(&out, "| `shed %s` | %s |\n", command.Signature(), strings.ReplaceAll(command.Summary, "|", `\|`))
	}
	return out.String()
}

// AgentContext is every document that goes into the consolidated agent-context
// file, in reading order.
type AgentContext struct {
	Skill    string // SKILL.md content, frontmatter included
	Starlark string // the generated SHED language reference
	Schema   string // the SHED.hcl schema reference
	Commands string // the generated CLI reference
	Errors   string // the error-code reference
}

// RenderAgentContext concatenates the whole documentation set into one
// self-contained file in the llms-full.txt shape: a title, a one-line summary
// taken from the skill's own description, then every document in full. The
// result is context an agent can be handed whole, with no other file needed.
func RenderAgentContext(input AgentContext) string {
	summary, body := splitSkillFrontmatter(input.Skill)

	var out strings.Builder
	out.WriteString("<!-- Generated by shed-docs from the committed documentation set. Do not edit by hand. -->\n\n")
	out.WriteString("# shed\n\n")
	if summary != "" {
		out.WriteString("> " + summary + "\n\n")
	}
	out.WriteString("This file is the complete shed documentation in one place, for use as model context.\n")
	for _, section := range []string{body, input.Starlark, input.Schema, input.Commands, input.Errors} {
		out.WriteString("\n---\n\n")
		out.WriteString(strings.TrimSpace(section) + "\n")
	}
	return tidy(out.String())
}

// splitSkillFrontmatter separates the YAML frontmatter from the skill body and
// pulls the description out of it, so the consolidated file opens with the
// same summary the skill declares rather than a second hand-written one.
func splitSkillFrontmatter(skill string) (description, body string) {
	rest, found := strings.CutPrefix(skill, "---\n")
	if !found {
		return "", skill
	}
	frontmatter, body, found := strings.Cut(rest, "\n---\n")
	if !found {
		return "", skill
	}
	for _, line := range strings.Split(frontmatter, "\n") {
		if value, ok := strings.CutPrefix(line, "description: "); ok {
			description = strings.TrimSpace(value)
		}
	}
	// The description's first sentence summarizes shed; the rest is skill
	// trigger routing, which means nothing outside a skill harness.
	if first, _, found := strings.Cut(description, ". "); found {
		description = first + "."
	}
	return description, body
}

// tidy collapses the blank-line runs that range blocks leave behind, so the
// generated markdown is stable and reviewable rather than ragged.
func tidy(content string) string {
	lines := strings.Split(content, "\n")
	var kept []string
	blanks := 0
	for _, line := range lines {
		if strings.TrimSpace(line) == "" {
			blanks++
			if blanks > 1 {
				continue
			}
		} else {
			blanks = 0
		}
		kept = append(kept, strings.TrimRight(line, " \t"))
	}
	return strings.TrimRight(strings.Join(kept, "\n"), "\n") + "\n"
}
